### ISSUE TITLE
Tests timing out and not locking resources

### ISSUE THREAD

**Issue by mcquaiga** [mcquaiga/EvcProver#225]
If the test is left hanging too long the application seems to time out and you’re unable to complete the remaining tests. You need to back out and start from scratch.

**Comment by mcquaiga** [comment]
2019-10-16 10:51:37.6718|ERROR|Prover.GUI.Screens.Modules.QAProver.Screens.TestRunViewModel|System.UnauthorizedAccessException: Access Denied: COM9
   at RJCP.IO.Ports.Native.WinNativeSerial.WinIOError() in c:\Users\jcurl\Documents\Programming\HELIOS\serialportstream\code\Native\WinNativeSerial.cs:line 937
   at RJCP.IO.Ports.Native.WinNativeSerial.Open() in c:\Users\jcurl\Documents\Programming\HELIOS\serialportstream\code\Native\WinNativeSerial.cs:line 843
   at RJCP.IO.Ports.SerialPortStream.Open(Boolean setCommState) in c:\Users\jcurl\Documents\Programming\HELIOS\serialportstream\code\SerialPortStream.cs:line 246
   at RJCP.IO.Ports.SerialPortStream.Open() in c:\Users\jcurl\Documents\Programming\HELIOS\serialportstream\code\SerialPortStream.cs:line 216
   at Prover.CommProtocol.Common.IO.SerialPort.<Open>b__15_0() in C:\projects\prover\src\Prover.CommProtocol.Common\IO\SerialPort.cs:line 77
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Prover.CommProtocol.Common.IO.SerialPort.<Open>d__15.MoveNext() in C:\projects\prover\src\Prover.CommProtocol.Common\IO\SerialPort.cs:line 77
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Prover.CommProtocol.Common.EvcCommunicationClient.<>c__DisplayClass14_0.<<Connect>b__0>d.MoveNext() in C:\projects\prover\src\Prover.CommProtocol.Common\EvcCommunicationClient.cs:line 63
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Prover.CommProtocol.Common.EvcCommunicationClient.<Connect>d__14.MoveNext() in C:\projects\prover\src\Prover.CommProtocol.Common\EvcCommunicationClient.cs:line 94
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Prover.Core.VerificationTests.QaRunTestManager.<InitializeTest>d__28.MoveNext() in C:\projects\prover\src\Prover.Core\VerificationTests\QaRunTestManager.cs:line 154
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Prover.Core.VerificationTests.TestRunCreator.<CreateTestRun>d__9.MoveNext() in C:\projects\prover\src\Prover.Core\VerificationTests\TestRunCreator.cs:line 91
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Prover.GUI.Screens.Modules.QAProver.Screens.TestRunViewModel.<StartNewQaTest>d__126.MoveNext()

**Comment by mcquaiga** [comment]
COM Port isn't getting released after a communication event times out.

**Comment by Wleveill** [comment]
Hey Adam,

I’m just getting back to this and I’m not sure why the com port isn’t being released?

**Comment by mcquaiga** [comment]
Those are just notes to myself. It's an issue in the code
